services:
  mysql:
    image: mysql:8.4
    container_name: springboot-7-day-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootcamp
      MYSQL_USER: bootcamp
      MYSQL_PASSWORD: bootcamp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - springboot_mysql_data:/var/lib/mysql

volumes:
  springboot_mysql_data:

